#!/usr/bin/env python3
"""
Usage: antipasti [--append] FILE [FILE …]
"""
#  Author: Klaus Alexander Seistrup <klaus@seistrup.dk>
# License: GNU General Public License v3+ ⌘ http://gplv3.fsf.org/
#
# [Metadata just above main() method]

import sys
import os
import pathlib
import argparse
import locale

from collections import deque
from pprint import pprint

try:
    from typing import Any, Deque, Dict, IO, List, Union
    assert sys.version_info >= (3, 6), 'Python 3.6+ required'
except (AssertionError, ImportError, ModuleNotFoundError) as oops:
    print(str(oops), file=sys.stderr)
    sys.exit(1)

_ = locale.setlocale(locale.LC_ALL, '')

# Standard IO
(STDIN, STDOUT, STDERR) = (sys.stdin, sys.stdout, sys.stderr)
# Environment variables
ENV = os.environ
# Should we print debug statements?
DEBUG = ENV.get('DEBUG', 'False')[0].upper() in '1JTY'  # 1/Ja/True/Yes

Error = Union[Exception, str]


def debug(head: str, data: Any) -> None:
    """Possibly pretty print an object to stderr

    Args:
        head::str
            A label to associate with data
        data::Any
            Optional data to be shown

    Returns:
        nothing::None
    """
    if DEBUG:
        pprint(head if data is None else {head: data}, stream=STDERR)


def die(reason: Error = None) -> None:
    """Exit gracefully

    Args:
        reason::Error
            An optional string or exception.

    Returns:
        This method does not return, but exits with
            0 if no reason is given
            1 if an reason is given
    """
    debug('exit', reason)

    if reason:
        print(reason, file=STDERR)

    sys.exit(1 if reason else 0)


def resolve_name(fname: str) -> str:
    """Resolve the ‘canonical’ name of a file

    Args:
        fname::str
            The name of the file. The names ‘-’ and ‘+’ are
            shorthands for stdout resp. stderr.

    Returns:
        rname::str
            The canonical filename.
    """
    shorthands = {
        '-': '<stdout>',
        '+': '<stderr>',
        '<stdout>': '<stdout>',
        '<stderr>': '<stderr>',
    }

    if fname in shorthands:
        rname = shorthands[fname]
    else:
        fpath = pathlib.Path(fname)
        rpath = fpath.resolve()
        rname = rpath.as_posix()

    return rname


def open_file(fname: str, append: bool) -> IO:
    """Open a file for appending or writing

    Args:
        fname::str
            The name of the file to open. If the file is stdout
            or stderr, just duplicate the file descriptor.
        append::bool
            If true, open for writing, appending to the end of
            the file if it exists. Default is overwriting. The
            mode is ignored for standard IO.

    Returns:
        fptr::IO
            An open file pointer to the named file.
    """
    stdio = {
        '<stdout>': STDOUT,
        '<stderr>': STDERR,
    }

    if fname in stdio:
        orig = stdio[fname]
        fptr = open(os.dup(orig.fileno()), mode=orig.mode)
    else:
        fpath = pathlib.Path(fname)
        fptr = fpath.open('a' if append else 'w')

    return fptr


def open_streams(fnames: List[str], append: bool = False) -> Deque[IO]:
    """Open files for writing or appending

    Args:
        fnames::List[str]
            A list of files to open. The names ‘-’ and ‘+’ are
            shorthands for stdout resp. stderr.
        append::bool
            If true, open for writing, appending to the end of
            the file if it exists. Default is overwriting.

    Returns:
        streams::Deque[IO]
            A deque of open file pointers. Files are deduplicated
            and may appear more than once in the list.
    """
    streams: Deque[IO] = deque()
    cache: Dict[str, IO] = dict()

    for fname in fnames:
        rname = resolve_name(fname)

        if rname not in cache:
            cache[rname] = open_file(rname, append)

        streams.appendleft(cache[rname])

    return streams


def close_streams(streams: Deque[IO]) -> None:
    """Close a deque of open filepointers

    Args:
        streams::Deque[IO]
            A deque of open file pointers.

    Returns:
        nothing::None
    """
    for fptr in streams:
        fptr.close()


def antipasti(fptr: IO, streams: Deque[IO]) -> None:
    """Read from FPTR and write to open files in turn

    Args:
        fptr::IO
            A file pointer open for reading.
        streams::Deque([IO])
            A deque of open file pointers.

    Returns:
        nothing::None
    """
    for line in fptr:
        streams.rotate(1)
        streams[0].write(line)


############
# Metadata
__whoami__ = 'antipasti'
__revision__ = 1
__version__ = '2018.09.05-{}'.format(__revision__)
__author__ = 'Klaus Alexander Seistrup <klaus@seistrup.dk>'
__copyright__ = """\
antipasti {version}
Copyright © 2005-2018 {author}

This is free software; see the source for copying conditions. There is no
warranty; not even for merchantability or fitness for a particular purpose.\
""".format(version=__version__, author=__author__)
__epilog__ = """\
This program reads from standard input and writes to file1..fileN
such that lines 1, N+1, 2N+1, … are written to file1,
          lines 2, N+2, 2N+2, … are written to file2,
          et cetera.

Minus (‘-’) and plus (‘+’) are recognized as aliases for standard
input and standard error, respectively.\
"""
############


def main(progname: str = __whoami__) -> int:
    """Main entry point

    Args:
        progname::str
            An optional name for the program

    Returns:
        exitcode::int
    """
    debug('argv', sys.argv)

    parser = argparse.ArgumentParser(
        prog=progname,
        formatter_class=argparse.RawTextHelpFormatter,
        epilog=__epilog__
    )
    # Generic arguments
    parser.add_argument('-v', '--version', action='version',
                        version='%(prog)s/{}'.format(__version__),
                        help='show version information and exit')
    parser.add_argument('-c', '--copyright', action='version',
                        version=__copyright__,
                        help='show copying policy and exit')
    # Specific arguments
    parser.add_argument('-a', '--append', action='store_true',
                        help='append to the given FILEs, do not overwrite')
    parser.add_argument('FILE', nargs='+', help='filename')

    args = parser.parse_args()
    debug('args', args)

    try:
        streams = open_streams(args.FILE or ['-'], args.append)
        antipasti(STDIN, streams)
        close_streams(streams)
    except (KeyboardInterrupt, BrokenPipeError):
        die()
    except (FileNotFoundError, PermissionError) as error:
        die(error)
    except IsADirectoryError as error:
        die(error)
    except (IOError, OSError, MemoryError) as error:
        die(error)

    return 0


if __name__ == '__main__':
    sys.exit(main(pathlib.Path(sys.argv[0]).name))

# eof
